---
spring:
  profiles: cloud
management:
  port: -1

server:
  port: ${PORT:8989}

turbine:
  aggregator:
  clusterConfig: CATALOG-SERVICE
  appConfig: catalog-service
  InstanceMonitor:
    eventStream:
      skipLineLogic: false
  instanceUrlSuffix: /hystrix.stream
