---
spring:
  profiles: cloud
management:
  port: -1

server:
  port: ${PORT:8989}

turbine:
  aggregator:
    clusterConfig: ONLINEWEB
  appConfig: catalog-service,account-service,edge-service,inventory-service,order-service,user-service
