---
spring:
  profiles: cloud
management:
  port: -1

server:
  port: ${PORT:8989}

turbine:
  aggregator:
    clusterConfig: OnlineWebCluster
#  appConfig: catalog-service,inventory-service
  InstanceMonitor:
    eventStream:
      skipLineLogic: false
  instanceUrlSuffix: /hystrix.stream
#  clusterNameExpression: 'default'
  ConfigPropertyBasedDiscovery: 
    instances: catalog-service,inventory-service
