---
spring:
  profiles: cloud
management:
  port: -1

server:
  port: ${PORT:8989}

turbine:
  aggregator:
    clusterConfig: CATALOG-SERVICE,INVENTORY-SERVICE
  appConfig: catalog-service,inventory-service
  InstanceMonitor:
    eventStream:
      skipLineLogic: false
  instanceUrlSuffix: /hystrix.stream
  #clusterNameExpression: 'default'
