---
spring:
  profiles: cloud
management:
  port: -1

server:
  port: ${PORT:8989}

turbine:
  aggregator:
  appConfig: catalog-service,inventory-service
  clusterNameExpression: metadata['onlineweb']
  InstanceMonitor:
    eventStream:
      skipLineLogic:
        enabled: false
