spring.profiles.active: cloud
---
spring:
  profiles: cloud
management:
  port: -1

server:
  port: ${PORT:8989}

turbine:
  aggregator:
    clusterConfig: ONLINEWEB
  appConfig: catalog-service,account-service,edge-service,inventory-service,order-service,user-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
